# Generated by Django 4.2.6 on 2023-12-13 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
